# Generated by Django 5.1.1 on 2024-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(on_delete=models.Model, to='myapp.customer'),
        ),
    ]
